spring:
  # 配置SBA Client连接的安全账号密码
  security:
    user:
      name: admin
      password: admin
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://eureka:123456@localhost:8761/eureka/
      metadata-map:
        startup: ${random.int}    #needed to trigger info and endpoint update after restart
        user.name: ${spring.security.user.name}
        user.password: ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
# end::configuration-eureka[]

